version: "2"
services:
  web:
    image: odoo:15.0
    depends_on:
      - db
      
    ports:
      - "80:8069"
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
